# Generated by Django 2.1.5 on 2019-04-06 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='num_of_enrollments',
            field=models.IntegerField(blank=True, default=0, verbose_name='Enrollments'),
        ),
    ]
