# Generated by Django 2.1.5 on 2019-04-20 21:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseEnrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_enrolled', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date enrolled')),
                ('date_completed', models.DateTimeField(blank=True, null=True, verbose_name='date completed')),
                ('credit_earned', models.IntegerField(blank=True, default=0, help_text='Credit points a user has earned till now in the course', verbose_name='credit earned')),
                ('candidate', models.ForeignKey(help_text='Refers to the candidate who is taking on the associated course', on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='students',
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='course',
            field=models.ForeignKey(help_text='Refers to the course that the candidate has enrolled in', on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='core.Course'),
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='current_lesson',
            field=models.OneToOneField(blank=True, help_text='Refers to the last lesson the user had subscribe to', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Lesson'),
        ),
        migrations.AlterUniqueTogether(
            name='courseenrollment',
            unique_together={('candidate', 'course')},
        ),
    ]
