# Generated by Django 2.1.5 on 2019-03-08 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Field describes the date of birth which will help us find the age of the user', null=True, verbose_name='Date of Birth'),
        ),
    ]
