# Generated by Django 2.1.5 on 2019-03-11 17:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190308_2108'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('author', models.ForeignKey(help_text='Refers to the creator account of the course', on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('course', models.ForeignKey(help_text='Refers to the course this unit belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='units', to='core.Course')),
            ],
        ),
        migrations.AlterField(
            model_name='consumer',
            name='user',
            field=models.OneToOneField(help_text='Refers to the generic information that platform has collected on signup', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='consumer', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='producer',
            name='user',
            field=models.OneToOneField(help_text='Refers to the generic information that platform has collected on signup', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='producer', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assignment',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core.Unit'),
        ),
    ]
