# Generated by Django 2.1.5 on 2019-04-06 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_course_num_of_enrollments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='num_of_enrollments',
        ),
    ]
