# Generated by Django 2.1.5 on 2019-04-01 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190311_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumer',
            name='courses',
            field=models.ManyToManyField(blank=True, null=True, related_name='students', to='core.Course'),
        ),
    ]
