# Generated by Django 2.1.5 on 2019-04-01 20:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_consumer_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumer',
            name='courses',
        ),
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(blank=True, null=True, related_name='enrolled_in', to=settings.AUTH_USER_MODEL),
        ),
    ]
