# Generated by Django 2.2.1 on 2019-07-08 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20190701_1811'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CourseEnrollment',
            new_name='CourseProgress',
        ),
        migrations.CreateModel(
            name='LessonCompleted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.IntegerField(blank=True, default=0, help_text="This field holds the record of which module's lesson user has  completed", verbose_name='module id')),
                ('lesson', models.IntegerField(blank=True, default=0, help_text='This field holds the record of which lesson user has  completed', verbose_name='lesson id')),
                ('enrollment', models.ForeignKey(help_text='link to which user and course we this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='completed_lessons', to='core.CourseProgress')),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentCompleted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.IntegerField(blank=True, default=0, help_text="This field holds the record of which module's asignment user has completed", verbose_name='module id')),
                ('lesson', models.IntegerField(blank=True, default=0, help_text="This field holds the record of which lesson's assignment user has completed", verbose_name='lesson id')),
                ('assignment', models.IntegerField(blank=True, default=0, help_text='This field holds the record of which assignment user has completed', verbose_name='assignment id')),
                ('enrollment', models.ForeignKey(help_text='link to which user and course we this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='completed_assignments', to='core.CourseProgress')),
            ],
        ),
    ]
