# Generated by Django 2.2.1 on 2019-07-08 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20190708_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseprogress',
            name='current_assignment',
            field=models.OneToOneField(blank=True, help_text='Refers to the last assignment the user had subscribe to', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Assignment'),
        ),
    ]
