# Generated by Django 2.2.1 on 2019-07-15 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_courseprogress_current_assignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('feedback', models.TextField(blank=True, default='Test', null=True, verbose_name='feedback')),
            ],
        ),
    ]
