# Generated by Django 2.2.1 on 2019-07-19 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseprogress',
            name='current_assignment',
            field=models.ForeignKey(blank=True, help_text='Refers to the last assignment the user had subscribe to', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Assignment'),
        ),
        migrations.AlterField(
            model_name='courseprogress',
            name='current_lesson',
            field=models.ForeignKey(blank=True, help_text='Refers to the last lesson the user had subscribe to', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Lesson'),
        ),
    ]
